services:
  messenger-server:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    entrypoint: cargo run --release --bin messenger-server
    ports:
      - ${INTERNAL_GRPC_PORT}:${INTERNAL_GRPC_PORT}
    network_mode: host

  messenger-client:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    entrypoint: cargo run --release --bin messenger-client
    network_mode: host
    environment:
      - INTERNAL_GRPC_HOST=host.docker.internal
  
  redis:
    image: redis:latest
    network_mode: host
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
